# -*- coding: utf-8 -*-
"""D1_preprocessing_and_modeling22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r0Ex_3dWs8xM9qTsVwkqax5DGuOSthuT
"""

import time
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.dummy import DummyRegressor
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

"""# Merge"""

path1 = "/content/nykaa_campaign_data.csv"
path2 = "/content/purplle_campaign_data.csv"
path3 = "/content/tira_campaign_data.csv"

nykaa = pd.read_csv(path1)
purplle = pd.read_csv(path2)
tira = pd.read_csv(path3)

print(nykaa.shape)
print(purplle.shape)
print(tira.shape)

nykaa["Brand"] = "Nykaa"
purplle["Brand"] = "Purplle"
tira["Brand"] = "Tira"

df = pd.concat([nykaa, purplle, tira], ignore_index=True)
print(df.shape)
print(df["Brand"].value_counts())

"""# **EDA**"""

df.info()

df.describe()

print("Missing values:")
print(df.isnull().sum())
print()
print("Duplicated rows:", df.duplicated().sum())

for col in ["Campaign_Type", "Target_Audience", "Channel_Used", "Language", "Customer_Segment"]:
    print(df[col].value_counts())
    print()

pd.crosstab(df["Target_Audience"], df["Customer_Segment"])

print(df.groupby("Campaign_Type")["ROI"].mean().sort_values(ascending=False))
print()
print(df.groupby("Target_Audience")["ROI"].mean().sort_values(ascending=False))

plt.figure(figsize=(10, 7))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

print("Clicks > Impressions:", (df["Clicks"] > df["Impressions"]).sum())
print("Leads > Clicks:", (df["Leads"] > df["Clicks"]).sum())
print("Conversions > Leads:", (df["Conversions"] > df["Leads"]).sum())

# ensuring the law : ROI = Revenue / (Acquisition_Cost * Conversions) - 1
roi_formula = df["Revenue"] / (df["Acquisition_Cost"] * df["Conversions"]) - 1
diff = (roi_formula - df["ROI"]).abs()

print("Median diff:", diff.median())
print("Exact matches (<0.01):", (diff < 0.01).sum(), "/", len(df))
print("Correlation:", roi_formula.corr(df["ROI"]))

"""these columns (Revenue , Acquisition_Cost , Conversions) can't be used as a feature because of leakage so we changed the target from ROI to Conversions"""

ratio = df["Conversions"] / df["Leads"]
print(ratio.describe())

funnel_cols = ["Impressions", "Clicks", "Leads", "Conversions", "Revenue"]
print()
print(df[funnel_cols].corr())

"""# **Preprocessing**"""

df = df.drop("Campaign_ID", axis=1)

df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df = df.drop("Date", axis=1)

print(df["Year"].value_counts())

channels = ["Facebook", "WhatsApp", "Google", "YouTube", "Instagram", "Email"]

for channel in channels:
    df[channel] = df["Channel_Used"].str.contains(channel, regex=False).astype(int)

df = df.drop("Channel_Used", axis=1)
df.info()

df["Conversions"] = np.log1p(df["Conversions"])

target_col = "Conversions"

features = [
    "Impressions", "Clicks", "Leads",
    "Brand", "Campaign_Type", "Target_Audience", "Language", "Customer_Segment",
    "Duration", "Year", "Month",
    "Facebook", "WhatsApp", "Google", "YouTube", "Instagram", "Email",
]

X = df[features]
y = df[target_col]

print(X.shape, y.shape)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state= 42
)

print(X_train.shape, X_test.shape)

"""# **One Hot Encoding + Scaling**"""

categorical_features = [
    "Brand", "Campaign_Type", "Target_Audience", "Language", "Customer_Segment"
]

numerical_features = [
    "Impressions", "Clicks", "Leads",
    "Duration", "Year", "Month",
    "Facebook", "WhatsApp", "Google", "YouTube", "Instagram", "Email",
]

preprocessor_scaled = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
        ("num", StandardScaler(), numerical_features),
    ]
)

preprocessor_plain = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features),
    ],
    remainder="passthrough"
)

"""# **Modeling**"""

models = {
    "Baseline (Mean)": Pipeline([
        ("prep", preprocessor_plain),
        ("model", DummyRegressor(strategy="mean"))
    ]),
    "Ridge Regression": Pipeline([
        ("prep", preprocessor_scaled),
        ("model", Ridge(alpha=10))
    ]),
    "Decision Tree": Pipeline([
        ("prep", preprocessor_plain),
        ("model", DecisionTreeRegressor(
            max_depth=8, min_samples_leaf=5, random_state=42
        ))
    ]),
    "Random Forest": Pipeline([
        ("prep", preprocessor_plain),
        ("model", RandomForestRegressor(
            n_estimators=20, max_depth=14, min_samples_leaf=2,
            random_state=42, n_jobs=-1
        ))
    ]),
}

print("Models:", list(models))

results = []
trained_models = {}

for name, pipe in models.items():
    print(f"Training {name}...")
    start = time.time()

    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)

    cv_r2 = cross_val_score(pipe, X_train, y_train, cv=5, scoring="r2", n_jobs=-1)

    results.append({
        "Model": name,
        "RMSE": np.sqrt(mean_squared_error(y_test, y_pred)),
        "MAE": mean_absolute_error(y_test, y_pred),
        "R2 Score": r2_score(y_test, y_pred),
        "CV R2 (mean)": cv_r2.mean(),
        "CV R2 (std)": cv_r2.std(),
    })

    trained_models[name] = pipe
    print(f"  done in {time.time() - start:.1f}s")

results_df = pd.DataFrame(results).sort_values("R2 Score", ascending=False)
results_df

"""# **Feature Importance**"""

best_name = "Random Forest"
best_pipe = trained_models[best_name]

feature_names = best_pipe.named_steps["prep"].get_feature_names_out()
importances = best_pipe.named_steps["model"].feature_importances_

imp_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": importances
}).sort_values("Importance", ascending=False).head(15)

plt.figure(figsize=(9, 6))
sns.barplot(data=imp_df, x="Importance", y="Feature")
plt.title(f"Top 15 Features - {best_name}")
plt.tight_layout()
plt.show()

imp_df

"""# **Actual vs Predicted**"""

best_name = "Random Forest"
best_pipe = trained_models[best_name]

y_pred_best = best_pipe.predict(X_test)

y_test_real = np.expm1(y_test)
y_pred_real = np.expm1(y_pred_best)

plt.figure(figsize=(7, 7))
plt.scatter(y_test_real, y_pred_real, alpha=0.2, s=8)

min_val = min(y_test_real.min(), y_pred_real.min())
max_val = max(y_test_real.max(), y_pred_real.max())
plt.plot([min_val, max_val], [min_val, max_val], "r--")

plt.xlabel("Actual Conversions (Real Values)")
plt.ylabel("Predicted Conversions (Real Values)")
plt.title(f"Actual vs Predicted - {best_name}")
plt.show()

comparison_df = results_df[["Model", "RMSE", "MAE", "R2 Score", "CV R2 (mean)", "CV R2 (std)"]].copy()
comparison_df = comparison_df.reset_index(drop=True)
comparison_df.round(3)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].bar(results_df["Model"], results_df["MAE"], color="skyblue")
axes[0].set_title("MAE Comparison (Lower is Better)")
axes[0].tick_params(axis="x", rotation=30)

axes[1].bar(results_df["Model"], results_df["RMSE"], color="salmon")
axes[1].set_title("RMSE Comparison (Lower is Better)")
axes[1].tick_params(axis="x", rotation=30)

axes[2].bar(results_df["Model"], results_df["R2 Score"], color="lightgreen")
axes[2].set_title("R2 Score Comparison (Higher is Better)")
axes[2].tick_params(axis="x", rotation=30)

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, len(trained_models), figsize=(20, 4))

for ax, (name, pipe) in zip(axes, trained_models.items()):
    y_pred = pipe.predict(X_test)
    residuals = y_test - y_pred

    ax.scatter(y_pred, residuals, alpha=0.2, s=8)
    ax.axhline(0, color="red", linestyle="--")
    ax.set_title(name)
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Residual")

plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, len(trained_models), figsize=(20, 5))

for ax, (name, pipe) in zip(axes, trained_models.items()):
    y_pred = pipe.predict(X_test)

    ax.scatter(y_test, y_pred, alpha=0.2, s=8)
    ax.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], "r--")
    ax.set_title(name)
    ax.set_xlabel("Actual")
    ax.set_ylabel("Predicted")

plt.tight_layout()
plt.show()

cv_results = {}

for name, pipe in trained_models.items():
    if name == "Baseline (Mean)":
        continue
    scores = cross_val_score(pipe, X_train, y_train, cv=5, scoring="r2", n_jobs=-1)
    cv_results[name] = scores

cv_df = pd.DataFrame(cv_results)

plt.figure(figsize=(8, 5))
cv_df.boxplot()
plt.ylabel("R2 Score")
plt.title("Cross-Validation R2 Stability")
plt.show()

training_times = {}

for name, pipe in trained_models.items():
    start = time.time()
    pipe.fit(X_train, y_train)
    training_times[name] = time.time() - start

cv_range = cv_df.max() - cv_df.min()

summary_df = comparison_df.copy()
summary_df["CV_R2_range"] = summary_df["Model"].map(cv_range)
summary_df["Training_Time_s"] = summary_df["Model"].map(training_times)

summary_df